name: teenstar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.5
  dartz: ^0.10.0-nullsafety.2
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  implicitly_animated_reorderable_list: ^0.4.2
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kt_dart: ^1.0.0
  package_info_plus: ^3.0.2
  provider: ^6.0.4
  rxdart: ^0.27.7
  uuid: ^3.0.7
  flutter_signin_button: ^2.0.0
  easy_sidemenu: ^0.4.1
  sqflite: ^2.2.1
  shared_preferences: ^2.0.15
  #pdf: ^3.8.4
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  url_launcher: ^6.1.7
  syncfusion_flutter_pdf: ^20.4.52
  flutter_full_pdf_viewer: ^1.0.6

dev_dependencies:
  build_runner: ^2.2.0
  connectivity_plus: ^2.3.6+1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lint: ^1.10.0
  test: ^1.21.4
  auto_route_generator: ^5.0.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/splash.jpg"

flutter:
  uses-material-design: true
  generate: true 

  fonts:
    - family: DejaVu
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf
        - asset: assets/fonts/DejaVuSans-Oblique.ttf
          style: italic
        - asset: assets/fonts/DejaVuSans-Bold.ttf
          weight: 700
  assets:
    - assets/guide.pdf
    - assets/logo_vide.png
    - assets/icon/logo.png
    - assets/icon_app/icon_hachurage.png
    - config/
    - assets/icon_observation/icon_autre.png
    - assets/icon_observation/icon_bleu_vide.png
    - assets/icon_observation/icon_douleur.png
    - assets/icon_observation/icon_evt_autre.png
    - assets/icon_observation/icon_evt_confidentielle.png
    - assets/icon_observation/icon_evt_fatigue.png
    - assets/icon_observation/icon_evt_maladie.png
    - assets/icon_observation/icon_evt_medicament.png
    - assets/icon_observation/icon_evt_perso1.png
    - assets/icon_observation/icon_evt_perso2.png
    - assets/icon_observation/icon_evt_stress.png
    - assets/icon_observation/icon_evt_voyage.png
    - assets/icon_observation/icon_mucus_depot_seche_blanc.png
    - assets/icon_observation/icon_mucus_nuageux.png
    - assets/icon_observation/icon_mucus_opaque_blanc_jaune.png
    - assets/icon_observation/icon_mucus_opaque_transparent.png
    - assets/icon_observation/icon_mucus_transparent_filant.png
    - assets/icon_observation/icon_mucus_visible.png
    - assets/icon_observation/icon_sang_flux+.png
    - assets/icon_observation/icon_sang_flux++.png
    - assets/icon_observation/icon_sang_traces.png
    - assets/icon_observation/icon_sang_vide.png
    - assets/icon_observation/icon_temperature_basale.png
    - assets/icon_observation/icon_vide.png
    - assets/icon_observation/icon_humeur_autre.png
    - assets/icon_observation/icon_humeur_bonne.png
    - assets/icon_observation/icon_humeur_changeante.png
    - assets/icon_observation/icon_humeur_pas_emotion.png
    - assets/icon_observation/icon_humeur_envie_tranquille.png
    - assets/icon_observation/icon_humeur_nervosite.png
    - assets/icon_observation/icon_humeur_neutre.png
    - assets/icon_observation/icon_humeur_tres_bonne.png
    - assets/icon_observation/icon_humeur_tristesse.png
    - assets/icon_app/icon_fleur_sommet.png
    - assets/icon_app/icon_guide_avance.png
    - assets/icon_app/icon_pdf.png
    - assets/icon_app/icon_principe_de_base.png
    - assets/icon/icon-assets/main_flower.png
    - assets/icon_observation/sensation/sensation_autre.png
    - assets/icon_observation/sensation/sensation_H.png
    - assets/icon_observation/sensation/sensation_L.png
    - assets/icon_observation/sensation/sensation_M.png
    - assets/icon_observation/sensation/sensation_np.png
    - assets/icon_observation/sensation/sensation_S.png
    - assets/icon_observation/douleurs/douleur_Autre.png
    - assets/icon_observation/douleurs/douleur_DS.png
    - assets/icon_observation/douleurs/douleur_DV.png
    - assets/icon_observation/douleurs/douleur_MT.png
    - assets/icon_observation/douleurs/douleur_Aucune.png



  